### ISSUE TITLE
Detect Spikes and Fit issue 

### ISSUE THREAD

**Issue by sarahjyang** [jtdbod/Nanosensor-Imaging-App#6]
Throws error:

Error using table (line 307)
'ROI Total' is not a valid variable name.

Error in generateSummary (line 35)
dataFill = table({numRois;'-'},{numSigs;'-'},...

Error in NanosensorImaging/DetectSpikesandFitButtonPushed (line 109)
            summaryData = generateSummary(app.results);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 309)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by jtdbod** [comment]
What version of MATLAB are you running? I can't seem to replicate the error. Perhas older version didn't allow using spaces for variable names in Tables but newer versions are more flexible? I can run it fine on both the breakroom Windows computer as well as my MBP2015.

**Comment by sarahjyang** [comment]
fixed after moving to computer with the new MATLAB update

**Comment by jtdbod** [comment]
Closing
