### ISSUE TITLE
Issues Saving fig

### ISSUE THREAD

**Issue by sarahjyang** [jtdbod/Nanosensor-Imaging-App#8]
Code Throws following error when trying to save generated figures:
Index in position 1 is invalid. Array indices must be positive
integers or logical values.

Error in generateReport (line 112)
        'EdgeColor',[cmap(normdf(i),:),0.5],'LineWidth',4);

Error in batchProcessTifs (line 50)
        generateReport(app);

Error in NanosensorImaging/BatchProcessButtonPushed (line 74)
            batchProcessTifs(app);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 335)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by jtdbod** [comment]
There was the potential to get a value of 0 when baselining and normalizing signal to determine a color for the colormap. This 0 was then used as an index in the colormap, throwing the error. This bug is fixed in version 1.3.3.
